import { jsPDF } from "jspdf";

export interface PdfLine {
  text: string;          // Main text (translation or tutor message)
  subtext?: string;      // Secondary text (original or user message)
  label?: string;        // e.g. "You", "Them", "Tutor"
  labelColor?: "blue" | "grey" | "amber"; // label badge color
}

interface PdfOptions {
  title: string;
  subtitle?: string;
  langLabel?: string;
  lines: PdfLine[];
}

const COLORS = {
  headerBg: [1, 11, 46] as [number, number, number],       // #010B2E
  accent: [41, 91, 219] as [number, number, number],        // #295BDB
  white: [244, 244, 244] as [number, number, number],
  black: [30, 30, 30] as [number, number, number],
  grey: [130, 130, 130] as [number, number, number],
  amber: [217, 119, 6] as [number, number, number],
  separator: [220, 220, 220] as [number, number, number],
};

export function generatePDF(opts: PdfOptions): jsPDF {
  const pdf = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageW = pdf.internal.pageSize.getWidth();
  const pageH = pdf.internal.pageSize.getHeight();
  const margin = 15;
  const contentW = pageW - margin * 2;
  let y = margin;

  const addPage = () => { pdf.addPage(); y = margin; };
  const checkSpace = (need: number) => { if (y + need > pageH - margin) addPage(); };

  // ── Header bar
  pdf.setFillColor(...COLORS.headerBg);
  pdf.rect(0, 0, pageW, 40, "F");
  pdf.setTextColor(...COLORS.white);
  pdf.setFontSize(20);
  pdf.setFont("helvetica", "bold");
  pdf.text("PolyGlot AI", margin, 18);
  pdf.setFontSize(10);
  pdf.setFont("helvetica", "normal");
  const dateStr = new Date().toLocaleDateString(undefined, {
    year: "numeric", month: "long", day: "numeric", hour: "2-digit", minute: "2-digit",
  });
  pdf.text(dateStr, margin, 28);
  if (opts.langLabel) {
    pdf.text(opts.langLabel, pageW - margin, 28, { align: "right" });
  }
  y = 50;

  // ── Title
  pdf.setTextColor(...COLORS.accent);
  pdf.setFontSize(14);
  pdf.setFont("helvetica", "bold");
  pdf.text(opts.title, margin, y);
  y += 6;

  if (opts.subtitle) {
    pdf.setFontSize(9);
    pdf.setFont("helvetica", "normal");
    pdf.setTextColor(...COLORS.grey);
    pdf.text(opts.subtitle, margin, y);
    y += 5;
  }

  // ── Separator
  pdf.setDrawColor(...COLORS.accent);
  pdf.setLineWidth(0.5);
  pdf.line(margin, y, pageW - margin, y);
  y += 8;

  // ── Lines
  if (opts.lines.length === 0) {
    pdf.setTextColor(100, 100, 100);
    pdf.setFontSize(11);
    pdf.setFont("helvetica", "italic");
    pdf.text("No messages.", margin, y);
  } else {
    opts.lines.forEach((line, idx) => {
      checkSpace(20);

      // Label badge
      if (line.label) {
        const color = line.labelColor === "amber" ? COLORS.amber
          : line.labelColor === "grey" ? COLORS.grey
          : COLORS.accent;
        pdf.setFillColor(...color);
        pdf.setTextColor(255, 255, 255);
        pdf.setFontSize(7);
        pdf.setFont("helvetica", "bold");
        const labelW = pdf.getTextWidth(line.label) + 4;
        pdf.roundedRect(margin, y - 3.5, labelW, 5, 1, 1, "F");
        pdf.text(line.label, margin + 2, y);
        y += 4;
      }

      // Main text
      pdf.setTextColor(...COLORS.black);
      pdf.setFontSize(11);
      pdf.setFont("helvetica", "bold");
      const mainLines = pdf.splitTextToSize(line.text, contentW);
      pdf.text(mainLines, margin, y);
      y += mainLines.length * 5.5;

      // Subtext
      if (line.subtext) {
        checkSpace(8);
        pdf.setTextColor(...COLORS.grey);
        pdf.setFontSize(9);
        pdf.setFont("helvetica", "italic");
        const subLines = pdf.splitTextToSize(line.subtext, contentW);
        pdf.text(subLines, margin, y);
        y += subLines.length * 4.5;
      }

      y += 4;

      // Separator
      if (idx < opts.lines.length - 1) {
        checkSpace(3);
        pdf.setDrawColor(...COLORS.separator);
        pdf.setLineWidth(0.2);
        pdf.line(margin, y - 2, pageW - margin, y - 2);
        y += 3;
      }
    });
  }

  // ── Footer
  pdf.setTextColor(160, 160, 160);
  pdf.setFontSize(8);
  pdf.setFont("helvetica", "normal");
  pdf.text("Generated by PolyGlot AI — polyglotai.app", pageW / 2, pageH - 8, { align: "center" });

  return pdf;
}

/** Save PDF and optionally share via Web Share API */
export async function exportAndShare(opts: PdfOptions, filename: string) {
  const pdf = generatePDF(opts);
  const blob = pdf.output("blob");

  // Try native share first (mobile)
  if (navigator.share && navigator.canShare) {
    const file = new File([blob], filename, { type: "application/pdf" });
    if (navigator.canShare({ files: [file] })) {
      try {
        await navigator.share({
          title: opts.title,
          files: [file],
        });
        return;
      } catch (e: any) {
        // User cancelled share — fall through to download
        if (e.name === "AbortError") return;
      }
    }
  }

  // Fallback: download
  pdf.save(filename);
}
