// All phrase texts used for translation (English canonical)
export const ALL_PHRASE_TEXTS = [
  // Emergency
  "I need a doctor",
  "Call an ambulance",
  "Call the police",
  "Help me please",
  "There is a fire",
  "I am allergic to...",
  "I am hurt",
  "I need to make an emergency call",
  "Take me to the hospital",
  "I need my medication",
  // Navigation
  "Where is...?",
  "I am lost",
  "I need a taxi",
  "Where is the nearest train station?",
  "Where is the bus stop?",
  "Turn left",
  "Turn right",
  "Go straight",
  "How do I get to this address?",
  "How far is it?",
  // Restaurant
  "The menu, please",
  "Water, please",
  "The bill, please",
  "I am allergic to nuts",
  "I am allergic to gluten",
  "I am lactose intolerant",
  "I am vegetarian",
  "A table for two, please",
  "What do you recommend?",
  "Not spicy, please",
  // Hotel
  "I have a reservation",
  "Can I have the room key?",
  "What is the WiFi password?",
  "Can you clean the room?",
  "I need a wake-up call",
  "The hot water is not working",
  "Can I leave my luggage here?",
  "What time is checkout?",
  "Is there parking?",
  "Where is the swimming pool?",
  // Airport
  "Where is passport control?",
  "I lost my luggage",
  "Where is gate...?",
  "My flight is delayed",
  "I need to change my flight",
  "Can I have a window seat?",
  "I have nothing to declare",
  "Where is duty free?",
  "How do I get to the city center?",
  "Here is my boarding pass",
  // Shopping
  "How much does this cost?",
  "Is there a discount?",
  "I am just looking",
  "Do you have a bigger size?",
  "Can I return this?",
  "Do you accept credit cards?",
  "Can I have a receipt?",
  "Can you ship this?",
  "Where are the fitting rooms?",
  "Can I pay in cash?",
];
